theme: jekyll-theme-hacker
title: Challenge Info & Submissions
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

<!-- description: learning how to github paageee -->
